<!DOCTYPE html>
<html lang="fr-FR">
<head>    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/vendor/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/style.css">
   <title></title>
     <style>
             
            /* a:link {
                color: white;
            }

            
            a:hover {
                color: #FF00FF;
            }

            selected link 
            
            .contain{
                width: 80%;
                margin-left: 10%;
                margin-right: 10%;
            }
            article{
                background-color: rgba(200, 200, 200, 0.9);
                padding-left:10px;
                padding-top: 10px;
                -webkit-border-radius: 10px 10px 10px 10px;
                border-radius: 10px 10px 10px 10px;
            }
            .content
            {
                height:150px;
                overflow: auto;
                background-color: white;
                width:98%;
            }
            
            h4{
                font-weight: bold;
                color:gray;
                @baseFontSize: 8px;
            }

            
            .title{
                font-weight: bold;
                color:yellow;
            }
             p{
                @baseFontSize: 8px;
            }
           
            section li{               
                display: inline-block;
                list-style: none;
                padding-right: 3px;
                margin-right: 1px;
                width: 20px;
                text-align: center;
               
                line-height: 25px;
            }
            .lineMessage{
                padding-right: 10px;
            }
            input[type="text"]{
                width:30%;
                height:20px;
            }
            input[type="password"]{
                 width:30%;
                height:20px;
            }
           
            .paginate_click
            {
                padding :5px;
            }
            .active{
                color: red;
            }  
            #messageError 
            {
                color: red;
            }   */

            body {
              padding-top: 10px;
            }
            [class*="col-"], footer {
              background-color:rgba(200, 200, 200, 0.9);
              border: 2px solid black;
              border-radius: 6px;
              line-height: 40px;
              text-align: center;
            }      
        </style>
</head>
<body>   
     <div class="container">
        <header>
            <div class="container">
                <nav class="navbar navbar-default">
                    <ul class="nav nav-tabs">
                        <li class="active"><a class= "accueil"  onclick="return false;">Accueil</a></li>
                        <li><a class= "admin"  onclick="return false;">Admin</a></li>
                        <li><a class= "NewPost"  onclick="return false;">New Post</a></li>
                        <li><a class= "contact"  onclick="return false;">Contact</a></li>
                    </ul>
             </nav>
            </div>
        </header>
        
        <div id = "body" class="container">
            <div class="row">
                <div class="col-md-8">
                     <div class="formulaire">

                    </div>


                    <section id="display">
                        
                    </section>                    
                </div>
                <div class="col-md-4">
                    <div class="aside"> ..
                        
                    </div>
                </div>
            </div>                
        </div>
        <footer>
            <div class="container"> 

            </div>
        </footer>
            
        
   </div> 
    <script src="/vendor/js/jquery-2.1.1.min.js"></script>   
    <script src="/vendor/js/bootstrap.min.js"></script>
    <script src="js/script.js"></script>

</body>
</html>