<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/vendor/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/style.css">
    <title>the Blog</title>
    <style type="text/css">
       body {
              padding-top: 50px;
            }
      /*[class*="col-"], footer {
              background-color:rgba(10, 20, 200, 0.1);
              border: 1px dashed black;
              border-radius: 6px;
            } */    
     /* Style pour l'exemple*/
      footer {
        border: 0;
      }
      article.col-sm-6, nav.col-sm-2 {
        
      }
      .input-xs {
        height: 22px;
        padding: 5px 5px;
        font-size: 12px;
        line-height: 1.5;
        border-radius: 3px;
        }
        
        .panel-body{
          text-align: justify;
          text-justify: inter-word;
        } 
        .panel-body img{
          width:100%;
          margin-bottom: 2px;
        }
        .panel-footer{
          font-size: 1em;
        } 
        .form-group{
           padding-bottom: 10px;
        }
        h2{
          color : #CCC;
          background-color: rgba(200, 200, 200, .4);
          text-align: center;
        }
        h3
        {
          text-align: center;
        }
       .btn-file {
            position: relative;
            overflow: hidden;
        }
        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
    </style>
  </head>
  <body>
    <div class="container">
      <header class="row">
        <div class="col-sm-12 col-lg-12">
          <h2 class="lead">Bienvenue sur le blog</h2>
        </div>
      </header>
     
      
           <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
              <ul class="nav navbar-nav">
                <li class="active"> <a class ="accueil" href="#" onclick="return false;">Home</a> </li>
                <li> <a class ="admin" href="#" onclick="return false;">Admin</a> </li>
                <li> <a class ="newpost" href="#" onclick="return false;">New post</a> </li>
                <li> <a class ="contact" href="#" onclick="return false;">Contact</a> </li>
              </ul>
              <form class="navbar-form navbar-right inline-form">
                <div class="form-group">
                  <input type="search" class="input-xs form-control" placeholder="Recherche">
                  <button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-eye-open"></span> Chercher</button>
                </div>
              </form>
            </div>
          </nav>
      
         <div class="main">
            <div class="row">
                <div class="col-sm-1">
                  
                </div>
                
                <div class="col-sm-3 formulaire">
                    
                </div>
                <div class="col-sm-8">
            
                </div>
              
            </div>
            <div class="row">
                <div class="col-sm-1">
                  
                </div>
                
                <div class="col-sm-10 list">
                    
                </div>
                <div class="col-sm-1">
            
                </div>
              
            </div>
             <div class="row">
                <section class="col-sm-12">
                  <div class="row">
                    <div class="col-sm-9">
                      <div class="row" id="display">
                        
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="row">
                        <aside class="col-sm-12">
                              <div class="panel panel-warning">
                                  <div class="panel-heading">
                                    <h3 class="panel-title"><span class="glyphicon glyphicon-pencil"> Latest Posts</h3>
                                  </div>

                                  <div class="panel-body">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a href="">Post1</a></li>
                                        <li class="list-group-item"><a href="">Post2</a></li>
                                        <li class="list-group-item"><a href="">Post3</a></li>
                                        <li class="list-group-item"><a href="">Post4</a></li>
                                        <li class="list-group-item"><a href="">Post5</a></li>
                                    </ul>
                                  </div>
                              </div>
                              <div class="panel panel-danger">
                                  <div class="panel-heading">
                                    <h3 class="panel-title"><span class="glyphicon glyphicon-folder-open"> Categories</h3>
                                  </div>
                                  <div class="panel-body">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a href="">categorie1</a></li>
                                        <li class="list-group-item"><a href="">categorie2</a></li>
                                        <li class="list-group-item"><a href="">categorie3</a></li>
                                        <li class="list-group-item"><a href="">Categorie4</a></li>
                                        <li class="list-group-item"><a href="">Categorie5</a></li>
                                    </ul>
                                  </div>
                              </div>
                               <div class="panel panel-info">
                                  <div class="panel-heading">
                                    <h3 class="panel-title"><span class="glyphicon glyphicon-bookmark"> Tags</h3>
                                  </div>
                                  <div class="panel-body">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a href="">Tag1</a></li>
                                        <li class="list-group-item"><a href="">Tag2</a></li>
                                        <li class="list-group-item"><a href="">Tag3</a></li>
                                        <li class="list-group-item"><a href="">Tag4</a></li>
                                        <li class="list-group-item"><a href="">Tag5</a></li>
                                    </ul>
                                  </div>
                              </div>
                              

                        </aside>
                       </div>
                    </div>
                  </div>
                </section>
             </div>   
         
        
               
        
            </div>
           <footer>
              <div class="container">
                  <hr />
                  <p class="text-center">Copyright © SOZ 2014. All rights reserved.</p>
              </div>
          </footer>
    </div>
     <script src="/vendor/js/jquery-2.1.1.min.js"></script>   
    <script src="/vendor/js/bootstrap.min.js"></script>
    <script src="js/script.js"></script>
  </body>
</html>