<!DOCTYPE html>
<html lang="fr-FR">
<head>    
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined-for-cwd.min.css">
    <link rel="stylesheet" href="css/style.css">
   <title></title>
     <style>
             
             a:link {
                color: white;
            }

            /* mouse over link */
            a:hover {
                color: #FF00FF;
            }

            /* selected link */
            
            .contain{
                width: 80%;
                margin-left: 10%;
                margin-right: 10%;
            }
            article{
                background-color: rgba(200, 200, 200, 0.9);
                padding-left:10px;
                padding-top: 10px;
                -webkit-border-radius: 10px 10px 10px 10px;
                border-radius: 10px 10px 10px 10px;
            }
            .content
            {
                height:150px;
                overflow: auto;
                background-color: white;
                width:98%;
            }
            
            h4{
                font-weight: bold;
                color:gray;
                @baseFontSize: 8px;
            }

            
            .title{
                font-weight: bold;
                color:yellow;
            }
             p{
                @baseFontSize: 8px;
            }
            ul{
                list-style-type: none;
                padding-left: 0px;
                margin-left: 0px;
            }
            nav li{
                display: inline-block;
                width: 80px;
                text-align: center;
                background-color: rgba(200, 200, 200, 0.9);
                -webkit-border-radius: 10px 10px 10px 10px;
                border-radius: 10px 10px 10px 10px;
                margin-top: 40px;
            }
            section li{               
                display: inline-block;
                list-style: none;
                padding-right: 3px;
                margin-right: 1px;
                width: 20px;
                text-align: center;
               
                line-height: 25px;
            }
            .lineMessage{
                padding-right: 10px;
            }
            input[type="text"]{
                width:60%;
                height:20px;
            }
            .paginate_click
            {
                padding :5px;
            }
            .active{
                color: red;
            }            
        </style>
</head>
<body>
    <div class="jumbotron"> 
        
            <nav>
                <ul>
                    <li><a class= "accueil"  onclick="return false;">Accueil</a></li>
                    <li><a class= "admin"  onclick="return false;">Admin</a></li>
                    <li><a class= "contact"  onclick="return false;">Contact</a></li>
                </ul>
            </nav>
        
            <div class="container">
                
            </div>
            <section id="display">
                
            </section>
        
    </div>
    <script src="/vendor/js/jquery-2.1.1.min.js"></script>   
    <script src="/vendor/js/bootstrap.min.js"></script>
    <script src="js/script.js"></script>
</body>
</html>