 <h4>New Post</h4>
<form class="well col-sm-offset-1 col-sm-11" enctype="multipart/form-data">
    <div class="row form-group">
      <label class="control-label col-sm-4" for="title">Title : </label>
      <div class="col-sm-8">
        <input id="title" type="text" class="form-control">
      </div>
    </div>
    <div class="row form-group">
      <label class="control-label col-sm-4" for="textarea">Content : </label>
      <div class="col-sm-8">
        <textarea id="content" type="textarea" class="form-control"></textarea>
       </div>
    </div>
    <div class="row form-group">
      <label class="control-label col-sm-4" for="category">Category </label>
      <div class="col-sm-8">
        <select id="category" class="form-control">
          <option>categorie1</option>
          <option>categorie2</option>
          <option>categorie3</option>
          <option>categorie4</option>
          <option>categorie5</option>
        </select>
      </div>
    </div>
   
    <div class="row form-group">
       
       <div class="form-group">
        <label class="control-label col-sm-4" for="keywords">keywords</label>
         <div class="col-sm-8">
            <input class="form-control" id="keywords" type="text">
         </div>
      </div>
     </div>
    
    <div class="row form-group"> 
      <div class="form-group">
        
          <span class="btn btn-sm btn-success btn-file col-sm-offset-2 col-sm-2">
            Add image... <input type="file">
           </span>
        
         <div class="col-sm-8">
            <input class="form-control" id="labelImage" type="text" readonly>
         </div>
       </div>
    </div>
    <div class="form-group">
            <div class="col-sm-12 text-right">
                <button id="btnPost" class="btn btn-sm btn-danger">Post</button>
            </div>
    </div>
   
  
 
</form>




 <!--div class="form-group">
      <label for="choix_bieres">Keyword</label>
      <input list="keywords" type="text" id="choix_bieres">
      <datalist id="keywords">
        <option value="keyword1">
        <option value="keyword2">
        <option value="keyword3">
        <option value="keyword4">
      </datalist>
    </div-->