 <h3>New Post</h3>
<form class="row well col-sm-12 container" enctype="multipart/form-data">
    <div class="row form-group">
      <label class="control-label col-sm-4" for="title">Title : </label>
      <div class="col-sm-8">
        <input id="title" type="text" class="form-control">
      </div>
    </div>
    <div class="row form-group">
      <label class="control-label col-sm-4" for="textarea">Content : </label>
      <div class="col-sm-8">
        <textarea id="content" type="textarea" class="form-control"></textarea>
       </div>
    </div>
    <div class="row form-group">
      <label class="control-label col-sm-4" for="category">Category </label>
      <div class="col-sm-8">
        <select id="category" class="form-control">
          <option>categorie1</option>
          <option>categorie2</option>
          <option>categorie3</option>
          <option>categorie4</option>
          <option>categorie5</option>
        </select>
      </div>
    </div>
   
    <div class="row form-group">
       
       <div class="form-group">
        <label class="control-label col-sm-4" for="keywords">keywords</label>
         <div class="col-sm-8">
            <input class="form-control" id="keywords" type="text" class="form-control">
         </div>
      </div>
     </div>
    <fieldset >
    <div class="row form-group"> 
      <div class="form-group">
        <label class="control-label col-sm-4" for="keywords">
          <span class="btn btn-default btn-file">
            Browse <input type="file">
           </span>
        </label>
         <div class="col-sm-8">
            <input class="form-control" id="keywords" type="text" class="form-control">
         </div>
    </div>
    <button id= "btnPost" onclick="return false">Post</button>
  </fieldset>
 
</form>




 <!--div class="form-group">
      <label for="choix_bieres">Keyword</label>
      <input list="keywords" type="text" id="choix_bieres">
      <datalist id="keywords">
        <option value="keyword1">
        <option value="keyword2">
        <option value="keyword3">
        <option value="keyword4">
      </datalist>
    </div-->