<form class="row well col-sm-12" enctype="multipart/form-data">
  <legend>New Post</legend>
    <div class="form-group">
      <label for="texte">Title : </label>
      <input id="title" type="text" class="form-control">
    </div>
    <div class="form-group">
      <label for="textarea">Content : </label>
      <textarea id="content" type="textarea" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label for="select">Category </label>
      <select id="select" class="form-control">
        <option>categorie1</option>
        <option>categorie2</option>
        <option>categorie3</option>
        <option>categorie4</option>
        <option>categorie5</option>
      </select>
    </div>
    <!--div class="form-group">
      <label for="choix_bieres">Keyword</label>
      <input list="keywords" type="text" id="choix_bieres">
      <datalist id="keywords">
        <option value="keyword1">
        <option value="keyword2">
        <option value="keyword3">
        <option value="keyword4">
      </datalist>
    </div-->
    <fieldset >
        <legend >
          Keywords
        </legend>
         <div class="form-group">
          <label class="col-sm-3" for="keyword1">keyword1 : </label>
          <input class="col-sm-9" id="keyword1" type="text" class="form-control">
        </div>
         <div class="form-group">
          <label class="col-sm-3" for="keyword2">keyword2 : </label>
          <input class="col-sm-9" id="keyword2" type="text" class="form-control">
        </div>
         <div class="form-group">
          <label class="col-sm-3" for="keyword3">keyword3 : </label>
          <input class="col-sm-9" id="keyword3" type="text" class="form-control">
        </div>
    </fieldset>
    <fieldset >
    <legend >Image</legend>
              <input class="col-sm-offset-2 col-sm-9" type="file" name="imagePost">
    </fieldset>
    <fieldset >
    <legend ></legend>
    <button>Post</button>
  </fieldset>
 
</form>